### ISSUE TITLE
Question: network usage?

### ISSUE THREAD

**Issue by Llorx** [nrkno/tv-automation-playout-gateway#70]
I plan to manage Sofie remotely with a Chrome browser. Sometimes I'll be under 3G or satellite connections so the bandwidth/network reliability is really limited. How much bandwidth should I expect?

I mean. If I tell it to play a video, is the video already in the _server_ and only the command is sent to it, or will the entire video frames be sent to the _server_ from the _client_?

The same for a lower third with dynamic info (like a countdown, or rankings or whatever), for example.

**Comment by nytamin** [comment]
What's sent over the network from the playout-gateway are only commands for playing things, no frames are sent over the wire (ie the bandwidth needed for the playout-gateway is quite low).

That being said, the commands sent by playout-gateway can be quite time-sensitive so latency is the real challenge. I highly recommend that:

* playout-gateway is network-wise close to the hardware you plan to control (on same local network, physically close).
* Sofie Core should connect to the playout-gateway over a wired connection.
* Web client could connect to Sofie Core over a 3G connection, satellite is not recommended due to latency. (don't count on getting any previews/thumbnails in the Sofie GUI working over 3G-speeds though.)

**Comment by Llorx** [comment]
That's nice. Thank you for answering.

The last point is what I was looking for :-) I thought that the playout-gateway should be in the client (still not installed Sofie so I'm a bit lost). I don't expect previews when working over 3G, but at least I can guess what is happening when I send commands.

Pretty nice tool you have there ^^

**Comment by nytamin** [comment]
Happy to help!
Be sure to read up on [concepts and architecture](https://sofie.gitbook.io/sofie-tv-automation/documentation/features-and-configuration/concepts-and-architecture) in the docs to get a better sense of how the components work together.
